### ISSUE TITLE
Agility makes OpenGL overflow

### ISSUE THREAD

**Issue by TrigonArts** [Harmonised7/project_mmo#17]
Narrative description of issue : 
The Mod will make chests, the player, beds, mobs, ... invisible after you get a certain amount of "Agility"-levelup.

Steps to reproduce the issue or crash:
Sprint-Jump for some time, (takes a few minutes in a new world) and gain "Agility" experience.
After a certain point, you will see that suddenly your hand will disapear in 1st person and also in 3rd person. And placed chests, beds will not be rendered aswell as entities. 

In this latest.log file, I've written "I can see the chest" when I could see the chests, then I did some Sprint-Jumping until i gained levelups and then the chests disapeared -> then i wrote "I cannot see the chest"

Link to latest.log:
[latest.log](https://github.com/Harmonised7/project_mmo/files/5762532/latest.log)

OS of Client computer: Windows 10 Home 64Bit

Version of JAVA on Client: Adopt Open JDK 8 update 241

Version of Minecraft: 1.16.4

Version of the Modpack: 0.5

Version of Forge: Forge / 1.16.4 / 35.1.28

List of ALL mods installed: https://www.curseforge.com/minecraft/modpacks/engineers-life-2

**Comment by LuckyGamingEU** [comment]
Well I got the same issue. I did it Like Trigon i wrote in the chat when the entities get invisable...

hope for fast progression on this issue 👍  

[latest.log](https://github.com/Harmonised7/project_mmo/files/5762573/latest.log)

**Comment by Gunner76th** [comment]
After testing within the above environment with version 3.39.9 I was unable to reproduce the issue. Additionally, when both users installed the modpack using GDLauncher and started new worlds with 3.39.9 they were unable to reproduce the issue as well. Testing with Curseforge was not possible due to multiple problems that Curseforge has, which preventing it from loading the modpack reliably or at all. 

I am personally considering this issue closed/resolved and have advised Dreams01 to update the within the modpack.

**Comment by Harmonised7** [comment]
I do not look at issues on Github. Please contact me on Discord, instead.
